#include <bgclib/Models/TBGC/Coeff.hpp>

// TBGC coefficient implementation.
//
// TBGC is represented as two coupled fields, phi and mu, in flattened order:
//
//   [ phi_0 ... phi_{N-1}  mu_0 ... mu_{N-1} ]
//
// This file computes A11, A12, and A21. The A22 identity block is generated by
// the operator builder because it is structural rather than a derived stencil.
// Boundary source contributions remain separate from matrix coefficients.

namespace bgc::models::tbgc {

PetscReal controlVolumeSpacing(const Grid1D& grid) noexcept {
    return grid.nx > 0 ? grid.length / static_cast<PetscReal>(grid.nx) : 0.0;
}

Coefficients computeCoefficients(const Grid1D& grid,
                                 const TimeConfig& time,
                                 const Constants& constants) {
    const PetscInt n = grid.nx;
    const PetscReal h = controlVolumeSpacing(grid);
    const PetscReal hinv = 1.0 / h;
    const PetscReal hinv2 = hinv * hinv;
    const PetscReal hinv3 = hinv2 * hinv;
    const PetscReal bv = constants.bv;
    const PetscReal bvh2 = bv * hinv2;
    const PetscReal bvh3 = bv * hinv3;
    const PetscReal dhdt = h / time.dt;

    Coefficients coefficients;

    {
        StencilSet& A = coefficients.A11;
        const PetscReal c3 = -80.0 * bvh3 / 27.0;
        const PetscReal c4 = 8.0 * bvh3 / 25.0;

        A.vol0.ncols = 3;
        A.vol0.col[0] = 0;
        A.vol0.coef[0] = dhdt + 40.0 * bvh3;
        A.vol0.col[1] = 1;
        A.vol0.coef[1] = c3;
        A.vol0.col[2] = 2;
        A.vol0.coef[2] = c4;

        A.interior.ncols = 1;
        A.interior.col[0] = 0;
        A.interior.coef[0] = dhdt;

        A.volNm1.ncols = 3;
        A.volNm1.col[0] = n - 3;
        A.volNm1.coef[0] = c4;
        A.volNm1.col[1] = n - 2;
        A.volNm1.coef[1] = c3;
        A.volNm1.col[2] = n - 1;
        A.volNm1.coef[2] = dhdt + 40.0 * bvh3;
    }

    {
        StencilSet& A = coefficients.A12;

        A.vol0.ncols = 2;
        A.vol0.col[0] = 0;
        A.vol0.coef[0] = 4.0 * hinv;
        A.vol0.col[1] = 1;
        A.vol0.coef[1] = -4.0 * hinv / 3.0;

        A.interior.ncols = 3;
        A.interior.col[0] = -1;
        A.interior.coef[0] = -hinv;
        A.interior.col[1] = 0;
        A.interior.coef[1] = 2.0 * hinv;
        A.interior.col[2] = 1;
        A.interior.coef[2] = -hinv;

        A.volNm1.ncols = 2;
        A.volNm1.col[0] = n - 2;
        A.volNm1.coef[0] = -4.0 * hinv / 3.0;
        A.volNm1.col[1] = n - 1;
        A.volNm1.coef[1] = 4.0 * hinv;
    }

    {
        StencilSet& A = coefficients.A21;
        const PetscReal c1 = 14.0 * bvh2 / 9.0;
        const PetscReal c2 = -3.0 * bvh2 / 25.0;

        A.vol0.ncols = 3;
        A.vol0.col[0] = 0;
        A.vol0.coef[0] = -(1.0 + 3.0 * bvh2);
        A.vol0.col[1] = 1;
        A.vol0.coef[1] = c1;
        A.vol0.col[2] = 2;
        A.vol0.coef[2] = c2;

        A.interior.ncols = 3;
        A.interior.col[0] = -1;
        A.interior.coef[0] = bvh2;
        A.interior.col[1] = 0;
        A.interior.coef[1] = -(1.0 + 2.0 * bvh2);
        A.interior.col[2] = 1;
        A.interior.coef[2] = bvh2;

        A.volNm1.ncols = 3;
        A.volNm1.col[0] = n - 3;
        A.volNm1.coef[0] = c2;
        A.volNm1.col[1] = n - 2;
        A.volNm1.coef[1] = c1;
        A.volNm1.col[2] = n - 1;
        A.volNm1.coef[2] = -(1.0 + 3.0 * bvh2);
    }

    return coefficients;
}

RHSCoefficients computeBoundaryRHS(const Grid1D& grid,
                                   const Constants& constants,
                                   const BoundarySet& boundaries,
                                   const PetscReal t) {
    const PetscReal h = controlVolumeSpacing(grid);
    const PetscReal h2 = h * h;
    const PetscReal hinv = 1.0 / h;
    const PetscReal hinv2 = hinv * hinv;
    const PetscReal hinv3 = hinv2 * hinv;
    const PetscReal bv = constants.bv;

    const BoundaryCondition& w1 = boundaries.west[0];
    const BoundaryCondition& w2 = boundaries.west[1];
    const BoundaryCondition& e1 = boundaries.east[0];
    const BoundaryCondition& e2 = boundaries.east[1];

    const PetscReal a1w = w1.alpha();
    const PetscReal b1w = w1.beta();
    const PetscReal a2w = w2.alpha();
    const PetscReal b2w = w2.beta();
    const PetscReal g1w = w1.gamma(t);
    const PetscReal g2w = w2.gamma(t);

    const PetscReal a1e = e1.alpha();
    const PetscReal b1e = e1.beta();
    const PetscReal a2e = e2.alpha();
    const PetscReal b2e = e2.beta();
    const PetscReal g1e = e1.gamma(t);
    const PetscReal g2e = e2.gamma(t);

    const PetscReal denow = b2w * a1w - b1w * a2w;
    const PetscReal denoe = b2e * a1e - b1e * a2e;

    RHSCoefficients rhs;

    {
        const PetscReal aux = 8.0 * hinv3 / (675.0 * denow);
        const PetscReal sp1 = (225.0 * h2 * b2w -
                               (1380.0 * a2w * h - 3152.0 * b2w) * bv) * g1w;
        const PetscReal sp2 = -(225.0 * h2 * b1w -
                                (1380.0 * a1w * h - 3152.0 * b1w) * bv) * g2w;
        rhs.b1.vol0 = (sp1 + sp2) * aux;
    }

    {
        const PetscReal aux = 8.0 * hinv2 * bv / (225.0 * denow);
        const PetscReal sp1 = -(15.0 * h * a2w + 44.0 * b2w) * g1w;
        const PetscReal sp2 = (15.0 * h * a1w + 44.0 * b1w) * g2w;
        rhs.b2.vol0 = (sp1 + sp2) * aux;
    }

    {
        const PetscReal aux = 8.0 * hinv3 / (675.0 * denoe);
        const PetscReal sp1 = (225.0 * h2 * b2e +
                               (1380.0 * a2e * h + 3152.0 * b2e) * bv) * g1e;
        const PetscReal sp2 = -(225.0 * h2 * b1e +
                                (1380.0 * a1e * h + 3152.0 * b1e) * bv) * g2e;
        rhs.b1.volNm1 = (sp1 + sp2) * aux;
    }

    {
        const PetscReal aux = 8.0 * hinv2 * bv / (225.0 * denoe);
        const PetscReal sp1 = (15.0 * h * a2e - 44.0 * b2e) * g1e;
        const PetscReal sp2 = -(15.0 * h * a1e - 44.0 * b1e) * g2e;
        rhs.b2.volNm1 = (sp1 + sp2) * aux;
    }

    return rhs;
}

DiscreteRHS buildBoundaryRHS(const Grid1D& grid, const RHSCoefficients& rhs) {
    const PetscInt n = grid.nx;
    return {
        .size = 2 * n,
        .entries = {
            {.row = 0, .value = rhs.b1.vol0},
            {.row = n - 1, .value = rhs.b1.volNm1},
            {.row = n, .value = rhs.b2.vol0},
            {.row = 2 * n - 1, .value = rhs.b2.volNm1},
        },
    };
}

} // namespace bgc::models::tbgc
